### PR TITLE
Add twitter and youtube badges

### PR DESCRIPTION
**Pull request by pmalirz**

### CODE REVIEW

**Review by spier — COMMENTED** [review]
Maybe we should be more specific about what this is? In the current form I find it a bit hard to tell what these numbers mean.

i.e. "twitter followers" and "youtube subscribers"?

**Comment by rrrutledge** [comment]
> "twitter followers" and "youtube subscribers"
That’s a good idea, @spier

**Comment by pmalirz** [comment]
Thanks for review guys! I've added logos to the badges. You should like it now. Let me know in case of any additional suggestions.

**Review by spier — APPROVED** [review]
Fancy, I like!

**Comment by rrrutledge** [comment]
Great work‼️

**Pull request merged**
